### ISSUE TITLE
Make this repository private?

### ISSUE THREAD

**Issue by pappalar** [joakim-ribier/komoot-challenge#2]
## Make this repository private?

Hello @joakim-ribier  

in order to ensure new candidates fairness, could you please make this repository private?

Thanks

**Comment by joakim-ribier** [comment]
Hello @racer1988

Ahhh yesssss sorry for that!

I know this test has not been approved by Komoot but if one day you are still looking a new candidate, I ready toooo.

Have a good day,

Joakim
